server:
  port: 9090

spring:
  application:
    name: ms-schneider-kafka-listener

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: customer-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.ms.schneider.dto.CustomerDTO
        spring.json.trusted.packages: "*"

  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/customerdb?authSource=admin

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.msvc.invex: DEBUG
    com.ms.schneider: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"